### ISSUE TITLE
Generating perturbated data

### ISSUE THREAD

**Issue by jS5t3r** [giladcohen/NNIF_adv_defense#11]
GPU: Titan V 12GB. 

I am running this command: 
```
python NNIF_adv_defense/attack.py --dataset cifar10 --set val --attack fgsm
``` 

The progress is slow and only makes 2% per night. In sum it takes over  one month. 

Is that normal? 
Would you be able to provide data?

![Image Pasted at 2021-10-27 15-48](https://user-images.githubusercontent.com/6324091/139281386-d30405c3-1b6e-4aad-81ee-d8c6063e665c.png)

**Comment by giladcohen** [comment]
Yes, this is normal. I used the implementation in darkon to calculate the hvp vectors and the influence scores. This code runs very slowly.
You can use my solution in the README and replace the attack.py script with the scripts in STAGE A and STAGE B instead. For STAGE A you will need to use your GPU. For STAGE B use only CPUs (the more the better) - with no GPU.

My trained models can be downloaded from:
CIFAR-10 model:
https://drive.google.com/file/d/18J82SNgughOgOicetJ0GMi8W0T1sU1eG/view?usp=sharing
CIFAR-100 model:
https://drive.google.com/file/d/1NO-VxmyOj98nwmDSqQOqBZTirf5JL88o/view?usp=sharing
SVHN model:
https://drive.google.com/file/d/1ubh_qrMVwHtOvfpY5z6naZrkYKK8xbuG/view?usp=sharing

The saved scores for them can be downloaded from:
https://drive.google.com/file/d/1z4WxdMCXFr2l77DTxLIV1IxlyXi_pWiZ/view?usp=sharing

Unfortunately all the adversarial images for all the attacks in the papers weight too much to save in the cloud. To generate these attacks, use STAGE-A and STAGE-B in the README.

**Comment by jS5t3r** [comment]
Thank you
